[build]
  command = "pnpm run build"
  publish = "dist"

[[headers]]
  for = "/admin"
  [headers.values]
    X-Robots-Tag = "noindex"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag = "noindex"
